use super::formula::{FormulaError, compile_formula, evaluate_formula};
use biblint_syntax::{Document, Entry, Item, Value};
use std::collections::{HashMap, HashSet};

/// The default key profile: the Google Scholar-style author/year/short-title
/// pattern, expressed using Better BibTeX's formula syntax.
pub const GOOGLE_SCHOLAR_FORMULA: &str = "auth.lower + year + shorttitle(1,0)";

const BETTER_BIBTEX_SKIP_WORDS: &[&str] = &[
    "a",
    "ab",
    "aboard",
    "about",
    "above",
    "across",
    "after",
    "against",
    "al",
    "along",
    "amid",
    "among",
    "an",
    "and",
    "anti",
    "around",
    "as",
    "at",
    "before",
    "behind",
    "below",
    "beneath",
    "beside",
    "besides",
    "between",
    "beyond",
    "but",
    "by",
    "d",
    "da",
    "das",
    "de",
    "del",
    "dell",
    "dello",
    "dei",
    "degli",
    "della",
    "dell",
    "delle",
    "dem",
    "den",
    "der",
    "des",
    "despite",
    "die",
    "do",
    "down",
    "du",
    "during",
    "ein",
    "eine",
    "einem",
    "einen",
    "einer",
    "eines",
    "el",
    "en",
    "et",
    "except",
    "for",
    "from",
    "gli",
    "i",
    "il",
    "in",
    "inside",
    "into",
    "is",
    "l",
    "la",
    "las",
    "le",
    "les",
    "like",
    "lo",
    "los",
    "near",
    "nor",
    "of",
    "off",
    "on",
    "onto",
    "or",
    "over",
    "past",
    "per",
    "plus",
    "round",
    "save",
    "since",
    "so",
    "some",
    "sur",
    "than",
    "the",
    "through",
    "to",
    "toward",
    "towards",
    "un",
    "una",
    "unas",
    "under",
    "underneath",
    "une",
    "unlike",
    "uno",
    "unos",
    "until",
    "up",
    "upon",
    "versus",
    "via",
    "von",
    "while",
    "with",
    "within",
    "without",
    "yet",
    "zu",
    "zum",
];

/// Return the unsuffixed key produced by biblint's default Google Scholar-style
/// formula.
#[must_use]
pub fn better_bibtex_key_base(entry: &Entry) -> Option<String> {
    better_bibtex_key_base_with_formula(entry, GOOGLE_SCHOLAR_FORMULA)
        .expect("the built-in Better BibTeX formula is valid")
}

/// Return an unsuffixed key generated by a Better BibTeX-compatible formula.
pub fn better_bibtex_key_base_with_formula(
    entry: &Entry,
    source: &str,
) -> Result<Option<String>, FormulaError> {
    let formula = compile_formula(source)?;
    evaluate_formula(&formula, entry)
}

/// Return one deterministic key suggestion per document item using biblint's
/// default Google Scholar-style formula. Non-entry items and entries without
/// enough key material return None.
#[must_use]
pub fn better_bibtex_key_suggestions(document: &Document) -> Vec<Option<String>> {
    better_bibtex_key_suggestions_with_formula(document, GOOGLE_SCHOLAR_FORMULA)
        .expect("the built-in Better BibTeX formula is valid")
}

/// Return deterministic key suggestions generated by a configured formula.
pub fn better_bibtex_key_suggestions_with_formula(
    document: &Document,
    source: &str,
) -> Result<Vec<Option<String>>, FormulaError> {
    let formula = compile_formula(source)?;
    let mut reserved = HashMap::<String, usize>::new();
    for entry in document.items.iter().filter_map(|item| match item {
        Item::Entry(entry) => Some(entry),
        _ => None,
    }) {
        if let Some(key) = entry.key.as_deref().filter(|key| !key.trim().is_empty()) {
            *reserved.entry(key.to_ascii_lowercase()).or_default() += 1;
        }
    }
    let mut used = HashSet::new();
    let mut suggestions = Vec::with_capacity(document.items.len());
    for item in &document.items {
        let Item::Entry(entry) = item else {
            suggestions.push(None);
            continue;
        };
        let base = evaluate_formula(&formula, entry)?;
        let Some(base) = base else {
            suggestions.push(None);
            continue;
        };
        if let Some(key) = entry.key.as_deref().filter(|key| !key.trim().is_empty()) {
            release_reserved_key(&mut reserved, key);
        }
        suggestions.push(Some(next_available_key(&base, &mut reserved, &mut used)));
    }
    Ok(suggestions)
}

fn release_reserved_key(reserved: &mut HashMap<String, usize>, key: &str) {
    let normalized = key.to_ascii_lowercase();
    if let Some(count) = reserved.get_mut(&normalized) {
        *count -= 1;
        if *count == 0 {
            reserved.remove(&normalized);
        }
    }
}

fn next_available_key(
    base: &str,
    reserved: &mut HashMap<String, usize>,
    used: &mut HashSet<String>,
) -> String {
    for duplicate in 0usize.. {
        let candidate = if duplicate == 0 {
            base.to_string()
        } else {
            format!("{base}{}", alphabetic_suffix(duplicate))
        };
        let normalized = candidate.to_ascii_lowercase();
        if !reserved.contains_key(&normalized) && used.insert(normalized) {
            return candidate;
        }
    }
    unreachable!("the finite key space should always contain an unused suffix")
}

pub(super) fn field_value<'a>(entry: &'a Entry, name: &str) -> Option<&'a Value> {
    entry
        .fields
        .iter()
        .find(|field| field.name.eq_ignore_ascii_case(name))
        .and_then(|field| field.value.as_ref())
        .filter(|value| !value.is_empty())
}

pub(super) fn split_creators(value: &str) -> Vec<String> {
    let mut creators = Vec::new();
    let mut start = 0usize;
    let mut depth = 0usize;
    let characters = value.char_indices().collect::<Vec<_>>();
    for (position, character) in &characters {
        match character {
            '{' if !is_escaped(value, *position) => depth += 1,
            '}' if !is_escaped(value, *position) => depth = depth.saturating_sub(1),
            'a' | 'A' if depth == 0 => {
                let end = *position + character.len_utf8();
                let Some(word) = value.get(*position..end + 2) else {
                    continue;
                };
                let previous = value[..*position].chars().next_back();
                let following = value[end + 2..].chars().next();
                if word.eq_ignore_ascii_case("and")
                    && previous.is_some_and(char::is_whitespace)
                    && following.is_some_and(char::is_whitespace)
                {
                    creators.push(value[start..*position].trim().to_string());
                    start = end + 2;
                }
            }
            _ => {}
        }
    }
    creators.push(value[start..].trim().to_string());
    creators
}

pub(super) fn creator_surname(value: &str, single_field: bool) -> String {
    let visible = visible_text(value).trim().to_string();
    if visible.is_empty() {
        return visible;
    }
    if single_field {
        return visible;
    }
    let parsed = parse_name(value);
    let family = parsed.family.trim();
    if family.is_empty() {
        visible
    } else {
        family.to_string()
    }
}

#[derive(Clone, Debug)]
struct ParsedName {
    family: String,
}

#[derive(Clone, Debug)]
enum NameToken {
    Word { value: String, prefix: bool },
    Comma,
}

pub(super) fn is_single_field_name(value: &str) -> bool {
    let trimmed = value.trim();
    outer_braced_text(trimmed).is_some()
}

fn outer_braced_text(value: &str) -> Option<&str> {
    if !value.starts_with('{') {
        return None;
    }
    let mut depth = 0usize;
    for (position, character) in value.char_indices() {
        if character == '{' && !is_escaped(value, position) {
            depth += 1;
        } else if character == '}' && !is_escaped(value, position) {
            depth = depth.checked_sub(1)?;
            if depth == 0 {
                return (position + character.len_utf8() == value.len())
                    .then_some(&value[1..position]);
            }
        }
    }
    None
}

fn parse_name(value: &str) -> ParsedName {
    let tokens = tokenize_name(value);
    let mut groups = vec![Vec::new()];
    for token in tokens {
        if matches!(token, NameToken::Comma) {
            groups.push(Vec::new());
        } else if let Some(group) = groups.last_mut() {
            group.push(token);
        }
    }

    let family = match groups.as_slice() {
        [] => String::new(),
        [only] => parse_uncomma_name(only),
        [family, _given] => words_to_string(family),
        [family, _suffix, _given, rest @ ..] => {
            let mut parsed_family = words_to_string(family);
            if parsed_family.is_empty() && !rest.is_empty() {
                parsed_family = words_to_string(&rest[0]);
            }
            parsed_family
        }
    };
    ParsedName { family }
}

fn parse_uncomma_name(tokens: &[NameToken]) -> String {
    let words = tokens
        .iter()
        .filter_map(name_token_value)
        .collect::<Vec<_>>();
    if words.len() <= 1 {
        return words_to_string(tokens);
    }

    let Some(prefix_start) = tokens.iter().position(name_token_is_prefix) else {
        return words[1..].join(" ");
    };
    let prefix_end = tokens[prefix_start..]
        .iter()
        .position(|token| !name_token_is_prefix(token))
        .map_or(tokens.len(), |offset| prefix_start + offset);
    let family = words_to_string(&tokens[prefix_end..]);
    if family.is_empty() {
        words_to_string(&tokens[prefix_start..prefix_end])
    } else {
        family
    }
}

fn tokenize_name(value: &str) -> Vec<NameToken> {
    let mut tokens = Vec::new();
    let mut current = String::new();
    let mut braces = 0usize;
    let flush = |tokens: &mut Vec<NameToken>, current: &mut String| {
        let word = current.trim();
        if !word.is_empty() {
            tokens.push(NameToken::Word {
                value: word.to_string(),
                prefix: word
                    .chars()
                    .next()
                    .is_some_and(|character| character.is_ascii_lowercase()),
            });
        }
        current.clear();
    };

    for (position, character) in value.char_indices() {
        if character == ',' && braces == 0 {
            flush(&mut tokens, &mut current);
            tokens.push(NameToken::Comma);
        } else if character.is_whitespace() && braces == 0 {
            flush(&mut tokens, &mut current);
        } else {
            if character == '{' && !is_escaped(value, position) {
                braces += 1;
            } else if character == '}' && !is_escaped(value, position) {
                braces = braces.saturating_sub(1);
            }
            current.push(character);
        }
    }
    flush(&mut tokens, &mut current);
    tokens
}

fn name_token_value(token: &NameToken) -> Option<&str> {
    match token {
        NameToken::Word { value, .. } => Some(value),
        NameToken::Comma => None,
    }
}

fn name_token_is_prefix(token: &NameToken) -> bool {
    matches!(token, NameToken::Word { prefix: true, .. })
}

fn words_to_string(tokens: &[NameToken]) -> String {
    tokens
        .iter()
        .filter_map(name_token_value)
        .map(str::trim)
        .filter(|word| !word.is_empty())
        .collect::<Vec<_>>()
        .join(" ")
}

fn is_escaped(source: &str, position: usize) -> bool {
    let bytes = source.as_bytes();
    let mut backslashes = 0usize;
    let mut previous = position;
    while previous > 0 && bytes[previous - 1] == b'\\' {
        backslashes += 1;
        previous -= 1;
    }
    backslashes % 2 == 1
}

pub(super) fn is_skip_word(word: &str) -> bool {
    BETTER_BIBTEX_SKIP_WORDS
        .iter()
        .any(|skip| word.eq_ignore_ascii_case(skip))
}

pub(super) fn capitalize_first(value: &str) -> String {
    if !value
        .chars()
        .next()
        .is_some_and(|character| character.is_ascii_alphabetic())
    {
        return value.to_string();
    }
    let mut result = String::new();
    if let Some(first) = value.chars().next() {
        result.extend(first.to_uppercase());
        result.push_str(&value[first.len_utf8()..]);
    }
    result
}

pub(super) fn clean_key_segment(value: &str) -> String {
    visible_text(value)
        .chars()
        .flat_map(fold_character)
        .filter(char::is_ascii_alphanumeric)
        .collect()
}

pub(super) fn visible_text(value: &str) -> String {
    let value = super::unescape_text(value, false);
    let characters = value.chars().collect::<Vec<_>>();
    let mut output = String::new();
    let mut position = 0usize;
    while position < characters.len() {
        if characters[position] == '\\' {
            position += 1;
            if position >= characters.len() {
                break;
            }
            if characters[position].is_ascii_alphabetic() {
                let command_start = position;
                while position < characters.len() && characters[position].is_ascii_alphabetic() {
                    position += 1;
                }
                let command = characters[command_start..position]
                    .iter()
                    .collect::<String>();
                if let Some(replacement) = tex_command_replacement(&command) {
                    output.push_str(replacement);
                }
            } else {
                output.push(characters[position]);
                position += 1;
            }
        } else if !matches!(characters[position], '{' | '}') {
            output.push(characters[position]);
            position += 1;
        } else {
            position += 1;
        }
    }
    output
}

fn tex_command_replacement(command: &str) -> Option<&'static str> {
    match command {
        "aa" => Some("a"),
        "AA" => Some("A"),
        "ae" => Some("ae"),
        "AE" => Some("AE"),
        "dj" | "dh" => Some("d"),
        "DJ" | "DH" => Some("D"),
        "ij" => Some("ij"),
        "IJ" => Some("IJ"),
        "l" => Some("l"),
        "L" => Some("L"),
        "ng" => Some("ng"),
        "NG" => Some("NG"),
        "oe" => Some("oe"),
        "OE" => Some("OE"),
        "o" => Some("o"),
        "O" => Some("O"),
        "ss" => Some("ss"),
        "SS" => Some("SS"),
        "th" => Some("th"),
        "TH" => Some("TH"),
        "i" => Some("i"),
        "j" => Some("j"),
        "LaTeX" => Some("LaTeX"),
        "TeX" => Some("TeX"),
        "BibTeX" => Some("BibTeX"),
        "XeLaTeX" => Some("XeLaTeX"),
        "LuaLaTeX" => Some("LuaLaTeX"),
        _ => None,
    }
}

pub(super) fn fold_character(character: char) -> Vec<char> {
    let replacement = match character {
        'À' | 'Á' | 'Â' | 'Ã' | 'Ä' | 'Å' | 'Ā' | 'Ă' | 'Ą' | 'Ǎ' | 'Ǻ' => "A",
        'à' | 'á' | 'â' | 'ã' | 'ä' | 'å' | 'ā' | 'ă' | 'ą' | 'ǎ' | 'ǻ' => "a",
        'Ć' | 'Ĉ' | 'Ċ' | 'Č' | 'Ç' => "C",
        'ć' | 'ĉ' | 'ċ' | 'č' | 'ç' => "c",
        'Ď' | 'Đ' | 'Ð' => "D",
        'ď' | 'đ' | 'ð' => "d",
        'È' | 'É' | 'Ê' | 'Ë' | 'Ē' | 'Ĕ' | 'Ė' | 'Ę' | 'Ě' => "E",
        'è' | 'é' | 'ê' | 'ë' | 'ē' | 'ĕ' | 'ė' | 'ę' | 'ě' => "e",
        'Ĝ' | 'Ğ' | 'Ġ' | 'Ģ' => "G",
        'ĝ' | 'ğ' | 'ġ' | 'ģ' => "g",
        'Ĥ' | 'Ħ' => "H",
        'ĥ' | 'ħ' => "h",
        'Ì' | 'Í' | 'Î' | 'Ï' | 'İ' | 'Ĩ' | 'Ī' | 'Ĭ' | 'Į' | 'Ǐ' => "I",
        'ì' | 'í' | 'î' | 'ï' | 'ı' | 'ĩ' | 'ī' | 'ĭ' | 'į' | 'ǐ' => "i",
        'Ĳ' => "IJ",
        'ĳ' => "ij",
        'Ĵ' => "J",
        'ĵ' => "j",
        'Ķ' => "K",
        'ķ' | 'ĸ' => "k",
        'Ĺ' | 'Ļ' | 'Ľ' | 'Ŀ' | 'Ł' => "L",
        'ĺ' | 'ļ' | 'ľ' | 'ŀ' | 'ł' => "l",
        'Ñ' | 'Ń' | 'Ņ' | 'Ň' | 'Ŋ' => "N",
        'ñ' | 'ń' | 'ņ' | 'ň' | 'ŋ' | 'ŉ' => "n",
        'Ò' | 'Ó' | 'Ô' | 'Õ' | 'Ö' | 'Ø' | 'Ō' | 'Ŏ' | 'Ő' | 'Ǒ' => "O",
        'ò' | 'ó' | 'ô' | 'õ' | 'ö' | 'ø' | 'ō' | 'ŏ' | 'ő' | 'ǒ' => "o",
        'Æ' => "AE",
        'æ' => "ae",
        'Œ' => "OE",
        'œ' => "oe",
        'ß' => "ss",
        'Þ' => "TH",
        'þ' => "th",
        'Ŕ' | 'Ŗ' | 'Ř' => "R",
        'ŕ' | 'ŗ' | 'ř' => "r",
        'Ś' | 'Ŝ' | 'Ş' | 'Š' => "S",
        'ś' | 'ŝ' | 'ş' | 'š' | 'ſ' => "s",
        'Ţ' | 'Ť' | 'Ŧ' => "T",
        'ţ' | 'ť' | 'ŧ' => "t",
        'Ù' | 'Ú' | 'Û' | 'Ü' | 'Ũ' | 'Ū' | 'Ŭ' | 'Ů' | 'Ű' | 'Ų' => "U",
        'ù' | 'ú' | 'û' | 'ü' | 'ũ' | 'ū' | 'ŭ' | 'ů' | 'ű' | 'ų' => "u",
        'Ŵ' => "W",
        'ŵ' => "w",
        'Ý' | 'Ŷ' | 'Ÿ' => "Y",
        'ý' | 'ŷ' | 'ÿ' => "y",
        'Ź' | 'Ż' | 'Ž' => "Z",
        'ź' | 'ż' | 'ž' => "z",
        'Ǆ' | 'Ǳ' => "DZ",
        'ǅ' | 'ǲ' => "Dz",
        'ǆ' | 'ǳ' => "dz",
        'Ǉ' => "LJ",
        'ǈ' => "Lj",
        'ǉ' => "lj",
        'Ǌ' => "NJ",
        'ǋ' => "Nj",
        'ǌ' => "nj",
        'ƒ' => "f",
        _ => return vec![character],
    };
    replacement.chars().collect()
}

fn alphabetic_suffix(mut number: usize) -> String {
    let mut suffix = String::new();
    while number > 0 {
        number -= 1;
        let character = char::from_u32(
            u32::from(b'a') + u32::try_from(number % 26).expect("remainder is below 26"),
        )
        .expect("alphabetic suffix is an ASCII letter");
        suffix.push(character);
        number /= 26;
    }
    suffix.chars().rev().collect()
}

#[cfg(test)]
mod tests {
    use super::{GOOGLE_SCHOLAR_FORMULA, better_bibtex_key_base, better_bibtex_key_suggestions};
    use biblint_syntax::parse;

    #[test]
    fn uses_the_google_scholar_default_formula() {
        let document = parse(
            r"@article{old,
              author = {Yang, X.},
              title = {Microscopic and atomistic mechanisms of sliding friction of MoS2},
              year = {2021}
            }",
        );
        let biblint_syntax::Item::Entry(entry) = &document.items[0] else {
            panic!("expected entry");
        };
        assert_eq!(
            GOOGLE_SCHOLAR_FORMULA,
            "auth.lower + year + shorttitle(1,0)"
        );
        assert_eq!(
            better_bibtex_key_base(entry).as_deref(),
            Some("yang2021Microscopic")
        );
    }

    #[test]
    fn falls_back_through_creator_fields_and_handles_corporate_names() {
        let document = parse(
            r"@book{one,editor={Babuška, A.},title={A Study},year=2020}
               @book{two,author={John Smith and Jane Doe},title={A Study},year=2020}
               @book{three,author={{World Health Organization}},title={A Report},year=2021}",
        );
        let entries = document
            .items
            .iter()
            .filter_map(|item| match item {
                biblint_syntax::Item::Entry(entry) => Some(entry),
                _ => None,
            })
            .collect::<Vec<_>>();
        let [first, second, third] = entries.as_slice() else {
            panic!("expected three entries");
        };
        assert_eq!(
            better_bibtex_key_base(first).as_deref(),
            Some("babuska2020Study")
        );
        assert_eq!(
            better_bibtex_key_base(second).as_deref(),
            Some("smith2020Study")
        );
        assert_eq!(
            better_bibtex_key_base(third).as_deref(),
            Some("worldhealthorganization2021Report")
        );
    }

    #[test]
    fn follows_bibtex_family_name_rules_for_particles_and_multiword_families() {
        let document = parse(
            r"@book{one,author={John Paul von der Rees Jones},title={A Study},year=2020}
               @book{two,author={Rees Jones, John Paul von der},title={A Study},year=2020}",
        );
        let entries = document
            .items
            .iter()
            .filter_map(|item| match item {
                biblint_syntax::Item::Entry(entry) => Some(entry),
                _ => None,
            })
            .collect::<Vec<_>>();
        let [first, second] = entries.as_slice() else {
            panic!("expected two entries");
        };
        assert_eq!(
            better_bibtex_key_base(first).as_deref(),
            Some("reesjones2020Study")
        );
        assert_eq!(
            better_bibtex_key_base(second).as_deref(),
            Some("reesjones2020Study")
        );
    }

    #[test]
    fn keeps_braced_single_field_names_and_latex_ligatures_intact() {
        let document = parse(
            r#"@book{one,author="{World Health Organization}",title={An \ae{} Study},year=2020}
               @book{two,author={M\"uller, Ada},title={A Study},year=2020}"#,
        );
        let entries = document
            .items
            .iter()
            .filter_map(|item| match item {
                biblint_syntax::Item::Entry(entry) => Some(entry),
                _ => None,
            })
            .collect::<Vec<_>>();
        let [first, second] = entries.as_slice() else {
            panic!("expected two entries");
        };
        assert_eq!(
            better_bibtex_key_base(first).as_deref(),
            Some("worldhealthorganization2020ae")
        );
        assert_eq!(
            better_bibtex_key_base(second).as_deref(),
            Some("muller2020Study")
        );
    }

    #[test]
    fn skips_better_bibtex_stop_words_and_does_not_invent_a_missing_year() {
        let document = parse(
            r"@book{one,author={Smith, Ada},title={The effects of NASA models},year={n.d.}}
               @book{two,author={Smith, Ada},title={A Study}}",
        );
        let entries = document
            .items
            .iter()
            .filter_map(|item| match item {
                biblint_syntax::Item::Entry(entry) => Some(entry),
                _ => None,
            })
            .collect::<Vec<_>>();
        let [first, second] = entries.as_slice() else {
            panic!("expected two entries");
        };
        assert_eq!(
            better_bibtex_key_base(first).as_deref(),
            Some("smitheffects")
        );
        assert_eq!(
            better_bibtex_key_base(second).as_deref(),
            Some("smithStudy")
        );
    }

    #[test]
    fn adds_better_bibtex_style_alpha_collision_suffixes() {
        let document = parse(
            "@article{one,author={Smith, J.},title={A Study},year=2020}\n@article{two,author={Smith, J.},title={A Study},year=2020}\n@article{three,author={Smith, J.},title={A Study},year=2020}",
        );
        let suggestions = better_bibtex_key_suggestions(&document)
            .into_iter()
            .flatten()
            .collect::<Vec<_>>();
        assert_eq!(
            suggestions,
            vec![
                "smith2020Study".to_string(),
                "smith2020Studya".to_string(),
                "smith2020Studyb".to_string()
            ]
        );
    }

    #[test]
    fn collision_suffixes_continue_after_z() {
        assert_eq!(super::alphabetic_suffix(1), "a");
        assert_eq!(super::alphabetic_suffix(26), "z");
        assert_eq!(super::alphabetic_suffix(27), "aa");
    }

    #[test]
    fn avoids_case_insensitive_collisions_with_existing_keys() {
        let document = parse(
            r"@misc{smithstudy2020a}
               @article{one,author={Smith, J.},title={A Study},year=2020}
               @article{two,author={Smith, J.},title={A Study},year=2020}",
        );
        let suggestions = better_bibtex_key_suggestions(&document)
            .into_iter()
            .flatten()
            .collect::<Vec<_>>();
        assert_eq!(suggestions[0], "smith2020Study");
        assert_eq!(suggestions[1], "smith2020Studya");
    }
}
