project:
  type: website

website:
  title: biblint
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: configuration.qmd
        text: Configuration
      - href: formatting.qmd
        text: Formatting
      - href: rules.qmd
        text: Rules
      - href: key-generation.md
        text: Citekeys
      - href: development.qmd
        text: Development

format:
  html:
    toc: true
    theme: cosmo
